project_id = "mtaeqtmcixlrudjsxcew"

[functions.save-push]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.push-public-key]
verify_jwt = false

[functions.cloudinary-sign]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

